### ISSUE TITLE
Change password

### ISSUE THREAD

**Issue by Amandeep-appzorro** [surixon/KitesSurffingApp#3]
[change password_Android.xlsx](https://github.com/surixon/KitesSurffingApp/files/1651913/change.password_Android.xlsx)

**Comment by ravinderappzorro** [comment]
[change.password_Android (2).xlsx](https://github.com/surixon/KitesSurffingApp/files/1663892/change.password_Android.2.xlsx)

**Comment by ravinderappzorro** [comment]
Done
