### ISSUE TITLE
Edit info

### ISSUE THREAD

**Issue by Amandeep-appzorro** [surixon/KitesSurffingApp#7]
[edit info android.xlsx](https://github.com/surixon/KitesSurffingApp/files/1691642/edit.info.android.xlsx)

**Comment by ravinderappzorro** [comment]
Close

**Comment by Amandeep-appzorro** [comment]
3 issues are pending out of 5 .pls check attached file.[edit.info.android.xlsx](https://github.com/surixon/KitesSurffingApp/files/1726814/edit.info.android.xlsx)

**Comment by ravinderappzorro** [comment]
Fixed
